### PR TITLE
Update URL template to include Region value

### PR DESCRIPTION
**Pull request by martinfoakes**
In the current Url setup, I was getting a `PermanentRedirect` error when trying to access assets within my bucket, the specified endpoint was incorrect.
Adding the `region` value to the Url fixed this and allowed me access

### CODE REVIEW

**Comment by robinmetral** [comment]
@DSchau can we merge this? This would likely fix long-running issue #8 :slightly_smiling_face:

**Comment by DSchau** [comment]
I’ll publish this later. @robinmetral remember this is free and open-source, and done in spare time.

Thanks for the bump.

**Comment by robinmetral** [comment]
Of course @DSchau, thanks a lot :raised_hands: ! Let me know if I can help with maintenance or development :slightly_smiling_face:

**Comment by Vacilando** [comment]
Any ETA on publishing this, @DSchau?

**Pull request merged**
